on: 
  push:
  workflow_dispatch:

jobs:
  test:
    name: API Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go

    - name: Download dependencies
      run: |
        go mod download

    - name: Output
      run: |
        echo "GIT_TOKEN: ${{ vars.GIT_TOKEN }}"

    - name: Download missing dependency
      if: steps.checkout.outputs.has-mod-changes == 'true'
      run: |
        go mod download github.com/stretchr/objx

    - name: Build and test
      run: |
        go build
        go test ./apps/gits
